### ISSUE TITLE
Compatibility with LS 5.2

### ISSUE THREAD

**Issue by esurface** [tpartner/LimeSurvey-Searchable-Dropdown#1]
Hi --- I'm looking for a Searchable Dropdown compatible with LimeSurvey v5.2.7.  Is it a quick update to make this work on that? Any alternatives I might use?

Thanks!

**Comment by forstem6** [comment]
Just a quick remark (in case you might not know): At least my 5.2.6 version allows to search in the dropdown field. After clicking on the dropdown just start typing and the best match will be automatically selected automatically. 
I admit it is not very userfriendly, because it does not indicate/suggest to the user that this will work. 

I was searching for the same answer and after finding your post here, I just gave it a shot and found the functionality.

**Comment by hakabe** [comment]
This script does not work on LimeSurvey 5.x. LS 4 is Discontinued. Any plans making a new script that supports version 5?

**Comment by hakabe** [comment]
Workaround to get this working in LS 5.0 is:
1. Edit the XML file and version to 5.0
2. Upload manually
3. Enable Question theme visibity on at Configuration > Themes > Question Themes > Visibility

**Comment by hakabe** [comment]
> Hi --- I'm looking for a Searchable Dropdown compatible with LimeSurvey v5.2.7. Is it a quick update to make this work on that? Any alternatives I might use?
> 
> Thanks!

I just left a solution for you

**Comment by tpartner** [comment]
It will be updated when time allows. I am quite aware of how to do it.

**Comment by tpartner** [comment]
Now updated for 5.x.
